#!/bin/sh
#first change the file names
#append '.' to change file in current directory
for D in $(find ./kepler4.3.1bvr -depth -name "*cvl*" -type d ) '.' 
do 
    #pushd $D >> /dev/null
    echo 'directory: ' "$D"
    echo 'change' "$D" 'to' `echo "$D" | sed 's/\(.*\)cvl/\1bvr/'`
    #change only the last occurence of cvl
    mv "$D" `echo "$D" | sed 's/\(.*\)cvl/\1bvr/'`
done
for D in $(find ./kepler4.3.1bvr -depth -name "*Cvl*" -type d ) '.' 
do 
    #pushd $D >> /dev/null
    echo 'directory: ' "$D"
    echo 'change' "$D" 'to' `echo "$D" | sed 's/\(.*\)Cvl/\1Cvr/'`
    #change only the last occurence of cvl
    mv "$D" `echo "$D" | sed 's/\(.*\)Cvl/\1Bvr/'`
done
for file in $(find ./kepler4.3.1bvr -name "*cvl*" -type f )
do
    echo 'file: ' "$file"
    echo 'change' "$file" 'to' `echo "$file" | sed s/cvl/bvr/g`
    mv "$file" `echo "$file" | sed s/cvl/bvr/g`
done
for file in $(find ./kepler4.3.1bvr -name "*Cvl*" -type f )
do
    echo 'file: ' "$file"
    echo 'change' "$file" 'to' `echo "$file" | sed s/Cvl/Bvr/g`
    mv "$file" `echo "$file" | sed s/Cvl/Bvr/g`
done
for file in $(find ./kepler4.3.1bvr -name "*CVL*" -type f )
do
    echo 'file: ' "$file"
    echo 'change' "$file" 'to' `echo "$file" | sed s/CVL/BVR/g`
    mv "$file" `echo "$file" | sed s/CVL/BVR/g`
done
echo 'searching for occurances cvl, Cvl, CVL in files'
for file in $(find ./kepler4.3.1bvr -name "*" -type f )
do
    echo 'file: ' "$file"
    sed -i 's/cvl/bvr/g' "$file"
    sed -i 's/Cvl/Bvr/g' "$file"
    sed -i 's/CVL/BVR/g' "$file"
done
