<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dvlconfig" nsURI="http://dvlconfig.ecore/1.0.0" nsPrefix="dvlconfig">
  <eClassifiers xsi:type="ecore:EClass" name="Config">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operators" lowerBound="1"
        upperBound="-1" eType="#//Operator" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" lowerBound="1"
        upperBound="-1" eType="#//Resource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="original" lowerBound="1"
        eType="#//Original" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="goals" lowerBound="1" upperBound="-1"
        eType="#//Goal" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realop" lowerBound="1"
        eType="#//Realop" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource" eSuperTypes="#//Locatable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Original" eSuperTypes="#//State"/>
  <eClassifiers xsi:type="ecore:EClass" name="Goal" eSuperTypes="#//State"/>
  <eClassifiers xsi:type="ecore:EClass" name="Locatable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State" abstract="true" eSuperTypes="#//Locatable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Realop" eSuperTypes="#//Locatable"/>
</ecore:EPackage>
