<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cvlsystemrelation" nsURI="http://cvlsystemrelation/1.0" nsPrefix="cvlsystemrelation">
  <eClassifiers xsi:type="ecore:EClass" name="CVLReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="relations" upperBound="-1"
        eType="#//VSpecRelation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cvl" eType="ecore:EClass ../../org.bangbangbang.cvl.model/model/CVLMetamodel.ecore#//VPackageable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSpecRelation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
        eType="ecore:EClass ../../org.bangbangbang.cvl.model/model/CVLMetamodel.ecore#//VSpec"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemVSpec" lowerBound="1"
        eType="ecore:EClass ../../org.bangbangbang.cvl.model/model/CVLMetamodel.ecore#//VSpec"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
        eType="#//AbstractChoiceReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractChoiceReference" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ChoiceReference" eSuperTypes="#//AbstractChoiceReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifiers" upperBound="-1"
        eType="#//VClassifierReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="choice" lowerBound="1"
        eType="ecore:EClass ../../org.bangbangbang.cvl.model/model/CVLMetamodel.ecore#//Choice"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChoiceGroup" eSuperTypes="#//AbstractChoiceReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="choices" upperBound="-1"
        eType="#//AbstractChoiceReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" lowerBound="1" eType="#//LogicalOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LogicalOperator">
    <eLiterals name="and"/>
    <eLiterals name="or" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VClassifierReference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantifier" lowerBound="1"
        eType="#//Quantifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vclassifier" lowerBound="1"
        eType="ecore:EClass ../../org.bangbangbang.cvl.model/model/CVLMetamodel.ecore#//VClassifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Quantifier">
    <eLiterals name="forAll"/>
    <eLiterals name="exist" value="1"/>
  </eClassifiers>
</ecore:EPackage>
