/**
 */
package cvl.provider;

import cvl.util.CvlAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class CvlItemProviderAdapterFactory extends CvlAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public CvlItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.Choice} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChoiceItemProvider choiceItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.Choice}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChoiceAdapter() {
		if (choiceItemProvider == null) {
			choiceItemProvider = new ChoiceItemProvider(this);
		}

		return choiceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.MultiplicityInterval} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MultiplicityIntervalItemProvider multiplicityIntervalItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.MultiplicityInterval}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMultiplicityIntervalAdapter() {
		if (multiplicityIntervalItemProvider == null) {
			multiplicityIntervalItemProvider = new MultiplicityIntervalItemProvider(this);
		}

		return multiplicityIntervalItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.VSpecDerivation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VSpecDerivationItemProvider vSpecDerivationItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.VSpecDerivation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVSpecDerivationAdapter() {
		if (vSpecDerivationItemProvider == null) {
			vSpecDerivationItemProvider = new VSpecDerivationItemProvider(this);
		}

		return vSpecDerivationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.VClassifier} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VClassifierItemProvider vClassifierItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.VClassifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVClassifierAdapter() {
		if (vClassifierItemProvider == null) {
			vClassifierItemProvider = new VClassifierItemProvider(this);
		}

		return vClassifierItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.ChoiceResolutuion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChoiceResolutuionItemProvider choiceResolutuionItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.ChoiceResolutuion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChoiceResolutuionAdapter() {
		if (choiceResolutuionItemProvider == null) {
			choiceResolutuionItemProvider = new ChoiceResolutuionItemProvider(this);
		}

		return choiceResolutuionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.VInstance} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VInstanceItemProvider vInstanceItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.VInstance}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVInstanceAdapter() {
		if (vInstanceItemProvider == null) {
			vInstanceItemProvider = new VInstanceItemProvider(this);
		}

		return vInstanceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.FragmentSubstitution} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FragmentSubstitutionItemProvider fragmentSubstitutionItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.FragmentSubstitution}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFragmentSubstitutionAdapter() {
		if (fragmentSubstitutionItemProvider == null) {
			fragmentSubstitutionItemProvider = new FragmentSubstitutionItemProvider(this);
		}

		return fragmentSubstitutionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.PlacementFragment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PlacementFragmentItemProvider placementFragmentItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.PlacementFragment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPlacementFragmentAdapter() {
		if (placementFragmentItemProvider == null) {
			placementFragmentItemProvider = new PlacementFragmentItemProvider(this);
		}

		return placementFragmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.ReplacementFragmentType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReplacementFragmentTypeItemProvider replacementFragmentTypeItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.ReplacementFragmentType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReplacementFragmentTypeAdapter() {
		if (replacementFragmentTypeItemProvider == null) {
			replacementFragmentTypeItemProvider = new ReplacementFragmentTypeItemProvider(this);
		}

		return replacementFragmentTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.Variabletype} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VariabletypeItemProvider variabletypeItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.Variabletype}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVariabletypeAdapter() {
		if (variabletypeItemProvider == null) {
			variabletypeItemProvider = new VariabletypeItemProvider(this);
		}

		return variabletypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.ObjectSubstitution} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ObjectSubstitutionItemProvider objectSubstitutionItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.ObjectSubstitution}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createObjectSubstitutionAdapter() {
		if (objectSubstitutionItemProvider == null) {
			objectSubstitutionItemProvider = new ObjectSubstitutionItemProvider(this);
		}

		return objectSubstitutionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.ObjectHandle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ObjectHandleItemProvider objectHandleItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.ObjectHandle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createObjectHandleAdapter() {
		if (objectHandleItemProvider == null) {
			objectHandleItemProvider = new ObjectHandleItemProvider(this);
		}

		return objectHandleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.BaseModelHandle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BaseModelHandleItemProvider baseModelHandleItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.BaseModelHandle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBaseModelHandleAdapter() {
		if (baseModelHandleItemProvider == null) {
			baseModelHandleItemProvider = new BaseModelHandleItemProvider(this);
		}

		return baseModelHandleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.Variable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VariableItemProvider variableItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.Variable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVariableAdapter() {
		if (variableItemProvider == null) {
			variableItemProvider = new VariableItemProvider(this);
		}

		return variableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.VariableValueAssignment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VariableValueAssignmentItemProvider variableValueAssignmentItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.VariableValueAssignment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVariableValueAssignmentAdapter() {
		if (variableValueAssignmentItemProvider == null) {
			variableValueAssignmentItemProvider = new VariableValueAssignmentItemProvider(this);
		}

		return variableValueAssignmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.PrimitveType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PrimitveTypeItemProvider primitveTypeItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.PrimitveType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPrimitveTypeAdapter() {
		if (primitveTypeItemProvider == null) {
			primitveTypeItemProvider = new PrimitveTypeItemProvider(this);
		}

		return primitveTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.ObjectType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ObjectTypeItemProvider objectTypeItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.ObjectType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createObjectTypeAdapter() {
		if (objectTypeItemProvider == null) {
			objectTypeItemProvider = new ObjectTypeItemProvider(this);
		}

		return objectTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.VInterface} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VInterfaceItemProvider vInterfaceItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.VInterface}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVInterfaceAdapter() {
		if (vInterfaceItemProvider == null) {
			vInterfaceItemProvider = new VInterfaceItemProvider(this);
		}

		return vInterfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.Constraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConstraintItemProvider constraintItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.Constraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConstraintAdapter() {
		if (constraintItemProvider == null) {
			constraintItemProvider = new ConstraintItemProvider(this);
		}

		return constraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.SlotAssignment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SlotAssignmentItemProvider slotAssignmentItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.SlotAssignment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSlotAssignmentAdapter() {
		if (slotAssignmentItemProvider == null) {
			slotAssignmentItemProvider = new SlotAssignmentItemProvider(this);
		}

		return slotAssignmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.ObjectExistence} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ObjectExistenceItemProvider objectExistenceItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.ObjectExistence}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createObjectExistenceAdapter() {
		if (objectExistenceItemProvider == null) {
			objectExistenceItemProvider = new ObjectExistenceItemProvider(this);
		}

		return objectExistenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.LinkEndSubstitution} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LinkEndSubstitutionItemProvider linkEndSubstitutionItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.LinkEndSubstitution}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLinkEndSubstitutionAdapter() {
		if (linkEndSubstitutionItemProvider == null) {
			linkEndSubstitutionItemProvider = new LinkEndSubstitutionItemProvider(this);
		}

		return linkEndSubstitutionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.LinkHandle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LinkHandleItemProvider linkHandleItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.LinkHandle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLinkHandleAdapter() {
		if (linkHandleItemProvider == null) {
			linkHandleItemProvider = new LinkHandleItemProvider(this);
		}

		return linkHandleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.ConfigurableUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConfigurableUnitItemProvider configurableUnitItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.ConfigurableUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConfigurableUnitAdapter() {
		if (configurableUnitItemProvider == null) {
			configurableUnitItemProvider = new ConfigurableUnitItemProvider(this);
		}

		return configurableUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.CVSpec} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CVSpecItemProvider cvSpecItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.CVSpec}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCVSpecAdapter() {
		if (cvSpecItemProvider == null) {
			cvSpecItemProvider = new CVSpecItemProvider(this);
		}

		return cvSpecItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.VConfiguration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VConfigurationItemProvider vConfigurationItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.VConfiguration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVConfigurationAdapter() {
		if (vConfigurationItemProvider == null) {
			vConfigurationItemProvider = new VConfigurationItemProvider(this);
		}

		return vConfigurationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.LinkExistence} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LinkExistenceItemProvider linkExistenceItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.LinkExistence}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLinkExistenceAdapter() {
		if (linkExistenceItemProvider == null) {
			linkExistenceItemProvider = new LinkExistenceItemProvider(this);
		}

		return linkExistenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.OpaqueVariationPoint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OpaqueVariationPointItemProvider opaqueVariationPointItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.OpaqueVariationPoint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOpaqueVariationPointAdapter() {
		if (opaqueVariationPointItemProvider == null) {
			opaqueVariationPointItemProvider = new OpaqueVariationPointItemProvider(this);
		}

		return opaqueVariationPointItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.OVPType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OVPTypeItemProvider ovpTypeItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.OVPType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOVPTypeAdapter() {
		if (ovpTypeItemProvider == null) {
			ovpTypeItemProvider = new OVPTypeItemProvider(this);
		}

		return ovpTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.OVPSemanticSpec} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OVPSemanticSpecItemProvider ovpSemanticSpecItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.OVPSemanticSpec}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOVPSemanticSpecAdapter() {
		if (ovpSemanticSpecItemProvider == null) {
			ovpSemanticSpecItemProvider = new OVPSemanticSpecItemProvider(this);
		}

		return ovpSemanticSpecItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.ObjectSpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ObjectSpecificationItemProvider objectSpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.ObjectSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createObjectSpecificationAdapter() {
		if (objectSpecificationItemProvider == null) {
			objectSpecificationItemProvider = new ObjectSpecificationItemProvider(this);
		}

		return objectSpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.ReplacementFragmentSpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReplacementFragmentSpecificationItemProvider replacementFragmentSpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.ReplacementFragmentSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReplacementFragmentSpecificationAdapter() {
		if (replacementFragmentSpecificationItemProvider == null) {
			replacementFragmentSpecificationItemProvider = new ReplacementFragmentSpecificationItemProvider(this);
		}

		return replacementFragmentSpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.VPackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VPackageItemProvider vPackageItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.VPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVPackageAdapter() {
		if (vPackageItemProvider == null) {
			vPackageItemProvider = new VPackageItemProvider(this);
		}

		return vPackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.ToBinding} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ToBindingItemProvider toBindingItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.ToBinding}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createToBindingAdapter() {
		if (toBindingItemProvider == null) {
			toBindingItemProvider = new ToBindingItemProvider(this);
		}

		return toBindingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.ToPlacement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ToPlacementItemProvider toPlacementItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.ToPlacement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createToPlacementAdapter() {
		if (toPlacementItemProvider == null) {
			toPlacementItemProvider = new ToPlacementItemProvider(this);
		}

		return toPlacementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.ToReplacement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ToReplacementItemProvider toReplacementItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.ToReplacement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createToReplacementAdapter() {
		if (toReplacementItemProvider == null) {
			toReplacementItemProvider = new ToReplacementItemProvider(this);
		}

		return toReplacementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.FromBinding} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FromBindingItemProvider fromBindingItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.FromBinding}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFromBindingAdapter() {
		if (fromBindingItemProvider == null) {
			fromBindingItemProvider = new FromBindingItemProvider(this);
		}

		return fromBindingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.FromPlacement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FromPlacementItemProvider fromPlacementItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.FromPlacement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFromPlacementAdapter() {
		if (fromPlacementItemProvider == null) {
			fromPlacementItemProvider = new FromPlacementItemProvider(this);
		}

		return fromPlacementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.FromReplacement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FromReplacementItemProvider fromReplacementItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.FromReplacement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFromReplacementAdapter() {
		if (fromReplacementItemProvider == null) {
			fromReplacementItemProvider = new FromReplacementItemProvider(this);
		}

		return fromReplacementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.VSpecRef} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VSpecRefItemProvider vSpecRefItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.VSpecRef}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVSpecRefAdapter() {
		if (vSpecRefItemProvider == null) {
			vSpecRefItemProvider = new VSpecRefItemProvider(this);
		}

		return vSpecRefItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.BCLExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BCLExpressionItemProvider bclExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.BCLExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBCLExpressionAdapter() {
		if (bclExpressionItemProvider == null) {
			bclExpressionItemProvider = new BCLExpressionItemProvider(this);
		}

		return bclExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.OpaqueConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OpaqueConstraintItemProvider opaqueConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.OpaqueConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOpaqueConstraintAdapter() {
		if (opaqueConstraintItemProvider == null) {
			opaqueConstraintItemProvider = new OpaqueConstraintItemProvider(this);
		}

		return opaqueConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.SlotValueExistence} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SlotValueExistenceItemProvider slotValueExistenceItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.SlotValueExistence}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSlotValueExistenceAdapter() {
		if (slotValueExistenceItemProvider == null) {
			slotValueExistenceItemProvider = new SlotValueExistenceItemProvider(this);
		}

		return slotValueExistenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.ParametricLinkEndSubstitution} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParametricLinkEndSubstitutionItemProvider parametricLinkEndSubstitutionItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.ParametricLinkEndSubstitution}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParametricLinkEndSubstitutionAdapter() {
		if (parametricLinkEndSubstitutionItemProvider == null) {
			parametricLinkEndSubstitutionItemProvider = new ParametricLinkEndSubstitutionItemProvider(this);
		}

		return parametricLinkEndSubstitutionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.ParametricObjectSubstitution} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParametricObjectSubstitutionItemProvider parametricObjectSubstitutionItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.ParametricObjectSubstitution}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParametricObjectSubstitutionAdapter() {
		if (parametricObjectSubstitutionItemProvider == null) {
			parametricObjectSubstitutionItemProvider = new ParametricObjectSubstitutionItemProvider(this);
		}

		return parametricObjectSubstitutionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.ParametricSlotAssignmet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParametricSlotAssignmetItemProvider parametricSlotAssignmetItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.ParametricSlotAssignmet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParametricSlotAssignmetAdapter() {
		if (parametricSlotAssignmetItemProvider == null) {
			parametricSlotAssignmetItemProvider = new ParametricSlotAssignmetItemProvider(this);
		}

		return parametricSlotAssignmetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.ChoiceDerivation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChoiceDerivationItemProvider choiceDerivationItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.ChoiceDerivation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChoiceDerivationAdapter() {
		if (choiceDerivationItemProvider == null) {
			choiceDerivationItemProvider = new ChoiceDerivationItemProvider(this);
		}

		return choiceDerivationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.VariableDerivation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VariableDerivationItemProvider variableDerivationItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.VariableDerivation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVariableDerivationAdapter() {
		if (variableDerivationItemProvider == null) {
			variableDerivationItemProvider = new VariableDerivationItemProvider(this);
		}

		return variableDerivationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.CVSpecDerivation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CVSpecDerivationItemProvider cvSpecDerivationItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.CVSpecDerivation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCVSpecDerivationAdapter() {
		if (cvSpecDerivationItemProvider == null) {
			cvSpecDerivationItemProvider = new CVSpecDerivationItemProvider(this);
		}

		return cvSpecDerivationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.ConfigurableUnitUsage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConfigurableUnitUsageItemProvider configurableUnitUsageItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.ConfigurableUnitUsage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConfigurableUnitUsageAdapter() {
		if (configurableUnitUsageItemProvider == null) {
			configurableUnitUsageItemProvider = new ConfigurableUnitUsageItemProvider(this);
		}

		return configurableUnitUsageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.PrimitiveValueSpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PrimitiveValueSpecificationItemProvider primitiveValueSpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.PrimitiveValueSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPrimitiveValueSpecificationAdapter() {
		if (primitiveValueSpecificationItemProvider == null) {
			primitiveValueSpecificationItemProvider = new PrimitiveValueSpecificationItemProvider(this);
		}

		return primitiveValueSpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.BCLConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BCLConstraintItemProvider bclConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.BCLConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBCLConstraintAdapter() {
		if (bclConstraintItemProvider == null) {
			bclConstraintItemProvider = new BCLConstraintItemProvider(this);
		}

		return bclConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.OperationCallExp} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperationCallExpItemProvider operationCallExpItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.OperationCallExp}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperationCallExpAdapter() {
		if (operationCallExpItemProvider == null) {
			operationCallExpItemProvider = new OperationCallExpItemProvider(this);
		}

		return operationCallExpItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.BooleanLiteralExp} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BooleanLiteralExpItemProvider booleanLiteralExpItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.BooleanLiteralExp}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBooleanLiteralExpAdapter() {
		if (booleanLiteralExpItemProvider == null) {
			booleanLiteralExpItemProvider = new BooleanLiteralExpItemProvider(this);
		}

		return booleanLiteralExpItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.StringLiteralExp} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StringLiteralExpItemProvider stringLiteralExpItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.StringLiteralExp}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStringLiteralExpAdapter() {
		if (stringLiteralExpItemProvider == null) {
			stringLiteralExpItemProvider = new StringLiteralExpItemProvider(this);
		}

		return stringLiteralExpItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.NumericLiteralExp} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NumericLiteralExpItemProvider numericLiteralExpItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.NumericLiteralExp}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNumericLiteralExpAdapter() {
		if (numericLiteralExpItemProvider == null) {
			numericLiteralExpItemProvider = new NumericLiteralExpItemProvider(this);
		}

		return numericLiteralExpItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.IntegerLiteralExp} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IntegerLiteralExpItemProvider integerLiteralExpItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.IntegerLiteralExp}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIntegerLiteralExpAdapter() {
		if (integerLiteralExpItemProvider == null) {
			integerLiteralExpItemProvider = new IntegerLiteralExpItemProvider(this);
		}

		return integerLiteralExpItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.UnlimitedLiteralExp} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UnlimitedLiteralExpItemProvider unlimitedLiteralExpItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.UnlimitedLiteralExp}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUnlimitedLiteralExpAdapter() {
		if (unlimitedLiteralExpItemProvider == null) {
			unlimitedLiteralExpItemProvider = new UnlimitedLiteralExpItemProvider(this);
		}

		return unlimitedLiteralExpItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cvl.RealLiteralExp} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RealLiteralExpItemProvider realLiteralExpItemProvider;

	/**
	 * This creates an adapter for a {@link cvl.RealLiteralExp}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRealLiteralExpAdapter() {
		if (realLiteralExpItemProvider == null) {
			realLiteralExpItemProvider = new RealLiteralExpItemProvider(this);
		}

		return realLiteralExpItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (choiceItemProvider != null) choiceItemProvider.dispose();
		if (multiplicityIntervalItemProvider != null) multiplicityIntervalItemProvider.dispose();
		if (vSpecDerivationItemProvider != null) vSpecDerivationItemProvider.dispose();
		if (vClassifierItemProvider != null) vClassifierItemProvider.dispose();
		if (choiceResolutuionItemProvider != null) choiceResolutuionItemProvider.dispose();
		if (vInstanceItemProvider != null) vInstanceItemProvider.dispose();
		if (fragmentSubstitutionItemProvider != null) fragmentSubstitutionItemProvider.dispose();
		if (placementFragmentItemProvider != null) placementFragmentItemProvider.dispose();
		if (replacementFragmentTypeItemProvider != null) replacementFragmentTypeItemProvider.dispose();
		if (variabletypeItemProvider != null) variabletypeItemProvider.dispose();
		if (objectSubstitutionItemProvider != null) objectSubstitutionItemProvider.dispose();
		if (objectHandleItemProvider != null) objectHandleItemProvider.dispose();
		if (baseModelHandleItemProvider != null) baseModelHandleItemProvider.dispose();
		if (variableItemProvider != null) variableItemProvider.dispose();
		if (variableValueAssignmentItemProvider != null) variableValueAssignmentItemProvider.dispose();
		if (primitveTypeItemProvider != null) primitveTypeItemProvider.dispose();
		if (objectTypeItemProvider != null) objectTypeItemProvider.dispose();
		if (vInterfaceItemProvider != null) vInterfaceItemProvider.dispose();
		if (constraintItemProvider != null) constraintItemProvider.dispose();
		if (slotAssignmentItemProvider != null) slotAssignmentItemProvider.dispose();
		if (objectExistenceItemProvider != null) objectExistenceItemProvider.dispose();
		if (linkEndSubstitutionItemProvider != null) linkEndSubstitutionItemProvider.dispose();
		if (linkHandleItemProvider != null) linkHandleItemProvider.dispose();
		if (configurableUnitItemProvider != null) configurableUnitItemProvider.dispose();
		if (cvSpecItemProvider != null) cvSpecItemProvider.dispose();
		if (vConfigurationItemProvider != null) vConfigurationItemProvider.dispose();
		if (linkExistenceItemProvider != null) linkExistenceItemProvider.dispose();
		if (opaqueVariationPointItemProvider != null) opaqueVariationPointItemProvider.dispose();
		if (ovpTypeItemProvider != null) ovpTypeItemProvider.dispose();
		if (ovpSemanticSpecItemProvider != null) ovpSemanticSpecItemProvider.dispose();
		if (objectSpecificationItemProvider != null) objectSpecificationItemProvider.dispose();
		if (replacementFragmentSpecificationItemProvider != null) replacementFragmentSpecificationItemProvider.dispose();
		if (vPackageItemProvider != null) vPackageItemProvider.dispose();
		if (toBindingItemProvider != null) toBindingItemProvider.dispose();
		if (toPlacementItemProvider != null) toPlacementItemProvider.dispose();
		if (toReplacementItemProvider != null) toReplacementItemProvider.dispose();
		if (fromBindingItemProvider != null) fromBindingItemProvider.dispose();
		if (fromPlacementItemProvider != null) fromPlacementItemProvider.dispose();
		if (fromReplacementItemProvider != null) fromReplacementItemProvider.dispose();
		if (vSpecRefItemProvider != null) vSpecRefItemProvider.dispose();
		if (bclExpressionItemProvider != null) bclExpressionItemProvider.dispose();
		if (opaqueConstraintItemProvider != null) opaqueConstraintItemProvider.dispose();
		if (slotValueExistenceItemProvider != null) slotValueExistenceItemProvider.dispose();
		if (parametricLinkEndSubstitutionItemProvider != null) parametricLinkEndSubstitutionItemProvider.dispose();
		if (parametricObjectSubstitutionItemProvider != null) parametricObjectSubstitutionItemProvider.dispose();
		if (parametricSlotAssignmetItemProvider != null) parametricSlotAssignmetItemProvider.dispose();
		if (choiceDerivationItemProvider != null) choiceDerivationItemProvider.dispose();
		if (variableDerivationItemProvider != null) variableDerivationItemProvider.dispose();
		if (cvSpecDerivationItemProvider != null) cvSpecDerivationItemProvider.dispose();
		if (configurableUnitUsageItemProvider != null) configurableUnitUsageItemProvider.dispose();
		if (primitiveValueSpecificationItemProvider != null) primitiveValueSpecificationItemProvider.dispose();
		if (bclConstraintItemProvider != null) bclConstraintItemProvider.dispose();
		if (operationCallExpItemProvider != null) operationCallExpItemProvider.dispose();
		if (booleanLiteralExpItemProvider != null) booleanLiteralExpItemProvider.dispose();
		if (stringLiteralExpItemProvider != null) stringLiteralExpItemProvider.dispose();
		if (numericLiteralExpItemProvider != null) numericLiteralExpItemProvider.dispose();
		if (integerLiteralExpItemProvider != null) integerLiteralExpItemProvider.dispose();
		if (unlimitedLiteralExpItemProvider != null) unlimitedLiteralExpItemProvider.dispose();
		if (realLiteralExpItemProvider != null) realLiteralExpItemProvider.dispose();
	}

}
