/**
 */
package no.sintef.bvr.table.resolution.custom;

import org.eclipse.emf.common.notify.Adapter;

import bvr.provider.BvrItemProviderAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support
 * Viewers. The adapters generated by this factory convert EMF adapter
 * notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}. The
 * adapters also support Eclipse property sheets. Note that most of the adapters
 * are shared among multiple instances. <!-- begin-user-doc --> <!--
 * end-user-doc -->
 * 
 * @generated
 */
public class CustomBvrItemProviderAdapterFactory extends
		BvrItemProviderAdapterFactory {

	/**
	 * This keeps track of the one adapter used for all
	 * {@link bvr.ConfigurableUnit} instances. <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * 
	 * @generated NOT Change ConfigurableUnitItemProvider to Custom
	 */
	protected CustomConfigurableUnitItemProvider configurableUnitItemProvider;

	/**
	 * This creates an adapter for a {@link bvr.ConfigurableUnit}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated NOT
	 */
	@Override
	public Adapter createConfigurableUnitAdapter() {
		if (configurableUnitItemProvider == null) {
			configurableUnitItemProvider = new CustomConfigurableUnitItemProvider(
					this);
		}

		return configurableUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all
	 * {@link bvr.ChoiceResolutuion} instances. <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * 
	 * @generated NOT
	 */
	protected CustomChoiceResolutuionItemProvider choiceResolutuionItemProvider;

	/**
	 * This creates an adapter for a {@link bvr.ChoiceResolutuion}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated NOT
	 */
	@Override
	public Adapter createChoiceResolutuionAdapter() {
		if (choiceResolutuionItemProvider == null) {
			choiceResolutuionItemProvider = new CustomChoiceResolutuionItemProvider(
					this);
		}

		return choiceResolutuionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all
	 * {@link no.sintef.bvr.model.VariableValueAssignment} instances. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated NOT
	 */
	protected CustomVariableValueAssignmentItemProvider variableValueAssignmentItemProvider;

	/**
	 * This creates an adapter for a
	 * {@link no.sintef.bvr.model.VariableValueAssignment}. <!-- begin-user-doc
	 * --> <!-- end-user-doc -->
	 * 
	 * @generated NOT
	 */
	@Override
	public Adapter createVariableValueAssignmentAdapter() {
		if (variableValueAssignmentItemProvider == null) {
			variableValueAssignmentItemProvider = new CustomVariableValueAssignmentItemProvider(
					this);
		}

		return variableValueAssignmentItemProvider;
	}

}